#!/usr/bin/env bash

set -e 

mkdir $HOME/.mujoco
wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O /tmp/mujoco.tar.gz
tar -xf /tmp/mujoco.tar.gz 
mv mujoco210 $HOME/.mujoco

echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco210/bin" >> ~/.bashrc
echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/lib/nvidia" >> ~/.bashrc
echo "export LD_PRELOAD=$CONDA_PREFIX/envs/mujoco/lib/libGLEW.so" >> ~/.bashrc
source ~/.bashrc

mamba env create -f linux.yml

